// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using demo.Data;

#nullable disable

namespace demo.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("demo.Models.JobRequest", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<string>("DeptName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndPoint1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndPoint2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndPoint3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndPoint4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoterFname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QN")
                        .HasColumnType("int");

                    b.Property<string>("QNAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QNName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QNSex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReqTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartPoint1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartPoint2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartPoint3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartPoint4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrgentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.ToTable("JobRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
